### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mgcrea** [wearefractal/vinyl-fs#70]
The `v1.0.0` tag is broken due to the missing `gulp-sourcemaps` dep. Could you please perform a new release so that the package is usable again?

**Comment by contra** [comment]
@mgcrea The gulp-sourcemaps stuff isn't published yet because it isn't finished, the code on master != the code that should be on npm all the time.

**Comment by mgcrea** [comment]
not sure how it happened, but we did pull a broken version from npm.

**Comment by markbirbeck** [comment]
> ...the code on master != the code that should be on npm all the time.

But the consequence of that seems to be that no other updates can be made if any one of the updates sitting in master aren't yet complete. Perhaps the sourcemap stuff could go into a branch or a forked repo until it's ready?

The reason I've stumbled onto this thread is because I was trying to use `file.extname` and it took me a while to realise that the reason it wasn't working for me was because `vinyl-fs` is not in sync with `vinyl`.

Looking at the commits I can see that someone has actually made the change to `package.json` and had it accepted to `master` but it's not yet been pushed to `npm`. And I can see now that it's because of this sourcemap issue.

**Comment by contra** [comment]
@markbirbeck Will do next time :+1:

**Comment by mgcrea** [comment]
@contra any update on a future release (with or without sourcemaps)?

**Comment by contra** [comment]
@mgcrea I need some people to test out the new sourcemaps stuff on master then I'll cut a release
